apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
  namespace: argocd
spec:
  replicas: 4
  selector:
    matchLabels:
      app: bus
  template:
    metadata:
      labels:
        app: bus
    spec:
      containers:
        - name: cont1
          image: nginx
          ports:
            - containerPort: 80
