apiVersion: apps/v1
kind: Deployment
metadata:
  name: nnn
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train
  template:
    metadata:
      labels:
        app: train
    spec:
      containers:
        - name: cont1
          image: nginx
          ports:
            - containerPort: 80
