apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce  # The volume will be mounted as read-write by a single node
  resources:
    requests:
      storage: "3Gi"  # The size requested by the claim
