apiVersion: v1
kind: Service
metadata:
  name: mysvc
spec:
  type: NodePort
  selector:
    app: bus
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # You can specify your desired NodePort here
